package com.swordfish.lemuroid.app.mobile.shared.compose.ui

import androidx.compose.ui.graphics.Color

/**
 * Retro pixel art palette.
 *
 * These values are mirrored in `res/values/material-colors.xml` so the Compose theme and the
 * XML window theme stay identical. Keep both files in sync when changing a colour.
 */
val md_theme_light_primary = Color(0xFF00796B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FFFE0)
val md_theme_light_onPrimaryContainer = Color(0xFF00382E)
val md_theme_light_secondary = Color(0xFF7A5900)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE08A)
val md_theme_light_onSecondaryContainer = Color(0xFF241A00)
val md_theme_light_tertiary = Color(0xFFA31D5B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFCCE4)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFD6D6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF4F5FF)
val md_theme_light_onBackground = Color(0xFF14162A)
val md_theme_light_surface = Color(0xFFF4F5FF)
val md_theme_light_onSurface = Color(0xFF14162A)
val md_theme_light_surfaceVariant = Color(0xFFDEE0F5)
val md_theme_light_onSurfaceVariant = Color(0xFF454A6B)
val md_theme_light_outline = Color(0xFF767B9E)
val md_theme_light_outlineVariant = Color(0xFFC6C9E2)
val md_theme_light_inverseOnSurface = Color(0xFFF4F5FF)
val md_theme_light_inverseSurface = Color(0xFF14162A)
val md_theme_light_inversePrimary = Color(0xFF4DE1C1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00796B)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4DE1C1)
val md_theme_dark_onPrimary = Color(0xFF00382E)
val md_theme_dark_primaryContainer = Color(0xFF005144)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FFFE0)
val md_theme_dark_secondary = Color(0xFFFFC44D)
val md_theme_dark_onSecondary = Color(0xFF402C00)
val md_theme_dark_secondaryContainer = Color(0xFF5C4200)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE08A)
val md_theme_dark_tertiary = Color(0xFFFF6FB5)
val md_theme_dark_onTertiary = Color(0xFF5C0033)
val md_theme_dark_tertiaryContainer = Color(0xFF83004A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFCCE4)
val md_theme_dark_error = Color(0xFFFF6B6B)
val md_theme_dark_errorContainer = Color(0xFF7A0000)
val md_theme_dark_onError = Color(0xFF4A0000)
val md_theme_dark_onErrorContainer = Color(0xFFFFD6D6)
val md_theme_dark_background = Color(0xFF0A0B18)
val md_theme_dark_onBackground = Color(0xFFDDE1F5)
val md_theme_dark_surface = Color(0xFF0A0B18)
val md_theme_dark_onSurface = Color(0xFFDDE1F5)
val md_theme_dark_surfaceVariant = Color(0xFF1E2038)
val md_theme_dark_onSurfaceVariant = Color(0xFF9EA2C4)
val md_theme_dark_outline = Color(0xFF5A5E85)
val md_theme_dark_outlineVariant = Color(0xFF2A2D48)
val md_theme_dark_inverseOnSurface = Color(0xFF14162A)
val md_theme_dark_inverseSurface = Color(0xFFDDE1F5)
val md_theme_dark_inversePrimary = Color(0xFF00796B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4DE1C1)
val md_theme_dark_scrim = Color(0xFF000000)
